string=input("Text:")
string=string.lower()
print("a: %s" % string.count("a") )
print("b: %s" % string.count("b") )
print("c: %s" % string.count("c") )
print("d: %s" % string.count("d") )
print("e: %s" % string.count("e") )
print("f: %s" % string.count("f") )
print("g: %s" % string.count("g") )
print("h: %s" % string.count("h") )
print("i: %s" % string.count("i") )
print("g: %s" % string.count("g") )
print("k: %s" % string.count("k") )
print("l: %s" % string.count("l") )
print("m: %s" % string.count("m") )
print("n: %s" % string.count("n") )
print("o: %s" % string.count("o") )
print("p: %s" % string.count("p") )
print("q: %s" % string.count("q") )
print("r: %s" % string.count("r") )
print("s: %s" % string.count("s") )
print("t: %s" % string.count("t") )
print("u: %s" % string.count("u") )
print("v: %s" % string.count("v") )
print("w: %s" % string.count("w") )
print("x: %s" % string.count("x") )
print("y: %s" % string.count("y") )
print("z: %s" % string.count("z") )